import { EnrollmentRequired, WorkspaceError, WorkspaceLoading } from '../../components/InternshipState';
import { useInternship } from '../../context/internshipContextValue';

export default function InternshipSummary() {
  const { data, loading, error, reload } = useInternship();
  if (loading) return <WorkspaceLoading />;
  if (error) return <WorkspaceError message={error} onRetry={reload} />;
  if (!data?.enrollment) return <EnrollmentRequired />;
  const { readiness, enrollment } = data;
  return <div className="space-y-5"><div><h1 className="text-2xl font-bold">Skill evidence timeline</h1><p className="text-sm text-[var(--text-muted)] mt-1">Explainable readiness based on reviews, evidence and communication—not course completion alone.</p></div><div className="grid md:grid-cols-4 gap-4">{[['Career readiness',readiness.career_readiness_score],['Technical',readiness.technical_score],['Communication',readiness.communication_score],['Average review',enrollment.avg_score]].map(([label,value]) => <div key={label} className="p-5 bg-[var(--bg-sidebar)] border border-[var(--border-color)] rounded-2xl"><div className="text-3xl font-bold text-emerald-600">{Number(value).toFixed(0)}</div><div className="text-xs font-bold text-[var(--text-muted)] mt-1">{label}</div></div>)}</div><section className="bg-[var(--bg-sidebar)] border border-[var(--border-color)] rounded-2xl p-6"><h2 className="font-bold">Dynamic skill graph</h2><p className="text-xs text-[var(--text-muted)] mt-1">{readiness.explanation}</p><div className="mt-5 space-y-4">{readiness.skills.map(item => <div key={item.skill}><div className="flex justify-between text-xs"><span className="font-bold">{item.skill} {item.verified ? <span className="text-emerald-600">✓ verified</span> : <span className="text-amber-600">· provisional</span>}</span><span>{item.proficiency}% · {item.evidence_count} evidence</span></div><div className="h-2 mt-2 bg-slate-500/10 rounded-full overflow-hidden"><div className="h-full bg-emerald-600" style={{ width: `${item.proficiency}%` }} /></div></div>)}{!readiness.skills.length && <p className="text-sm text-[var(--text-muted)]">Complete a project review to create your first skill evidence.</p>}</div></section><section className="bg-[var(--bg-sidebar)] border border-[var(--border-color)] rounded-2xl p-6"><h2 className="font-bold mb-4">Work history</h2><div className="space-y-3">{data.tasks.filter(item => item.submission).map(item => <div key={item.day} className="flex justify-between gap-4 p-3 border border-[var(--border-color)] rounded-xl"><div><div className="font-bold text-sm">Day {item.day} · {item.title}</div><div className="text-xs text-[var(--text-muted)] mt-1">Attempt {item.submission.attempt} · {item.submission.status.replace('_',' ')}</div></div><strong className="text-emerald-600">{item.submission.total_score ?? '—'}</strong></div>)}</div></section></div>;
}
